# Migrating from Travis CI guide: https://circleci.com/docs/2.0/migrating-from-travis/?section=getting-started

version: 2.1 # Circle CI 2.1

jobs:
  # "install" stage from Travis CI
  install:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - run: bash miniconda.sh -b -p $HOME/miniconda
      - run: source "$HOME/miniconda/etc/profile.d/conda.sh"
      - run: hash -r
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      
      # Useful for debugging any issues with conda
      - run: conda info -a
      
      - run: conda create -q -n test-environment python=3.8.8
      - run: conda activate test-environment
      - run: conda install -c conda-forge qgis=3.18.0 vispy=0.6.6 pyside2=5.13.2 gdal=3.2.1
      - run: conda install pytest six pytest-cov pytest-mock
      - run: conda install git pip
      - run: pip install git+https://github.com/noaa-ocs-hydrography/kluster.git#egg=hstb.kluster
      - run: pip install git+https://github.com/noaa-ocs-hydrography/shared.git#egg=hstb.shared
      - run: pip install -r requirements.txt

  # "script" stage from Travis CI
  script:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run: pytest tests